language: cpp
sudo: false
cache:
  - ccache
  - apt
addons:
  apt: &apt
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf2.13
      - yasm
      - texinfo
matrix:
  include:
    - os: linux
      compiler: clang
      services: docker
      before_install: docker build -t spidernode -f deps/spidershim/scripts/Dockerfile deps/spidershim/scripts
      script:
        - docker run -v `pwd`:/build spidernode
          sh -c "
            ./configure --engine=spidermonkey --debug &&
            make -k V=;
            ./deps/spidershim/scripts/run-tests.py
          "
      env: BUILD_CONFIG=normal ENABLE_DEBUG=true

    - os: linux
      compiler: gcc-4.8
      dist: trusty
      env: BUILD_CONFIG=normal ENABLE_DEBUG=true
      addons:
        apt:
          <<: *apt
          packages:
            - autoconf2.13
            - yasm
            - texinfo
            - g++-4.8
      install: export CC=gcc-4.8 CXX=g++-4.8

    - os: linux
      compiler: gcc-5
      dist: trusty
      env: BUILD_CONFIG=normal ENABLE_DEBUG=true
      addons:
        apt:
          <<: *apt
          packages:
            - autoconf2.13
            - yasm
            - texinfo
            - g++-5
      install: export CC=gcc-5 CXX=g++-5

    - os: linux
      compiler: clang
      dist: trusty
      env: BUILD_CONFIG=gczeal ENABLE_DEBUG=true

    - os: linux
      compiler: clang
      dist: trusty
      env: BUILD_CONFIG=normal ENABLE_ASAN=true ENABLE_DEBUG=true

    - os: osx
      compiler: clang
      env: BUILD_CONFIG=normal ENABLE_DEBUG=true

    - os: osx
      compiler: clang
      env: BUILD_CONFIG=gczeal MAKE_ARGS=-j2 ENABLE_DEBUG=true

    - os: osx
      compiler: clang-3.8
      osx_image: xcode7.3
      env: BUILD_CONFIG=normal ENABLE_ASAN=true MAKE_ARGS=-j2
      before_install:
        - wget http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz
        - tar xf clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz
        - brew update
        - brew tap homebrew/versions
        - brew unlink autoconf
        - brew install autoconf213
        - brew install yasm gawk ccache python
      install: export CC=$PWD/clang+llvm-3.8.0-x86_64-apple-darwin/bin/clang CXX=$PWD/clang+llvm-3.8.0-x86_64-apple-darwin/bin/clang++
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install autoconf213 yasm; fi
before_script:
  - ./configure $(if [ "$ENABLE_DEBUG" == "true" ]; then echo '--debug'; fi) --engine=spidermonkey $(if [ "$ENABLE_ASAN" == "true" ]; then echo "--enable-asan"; fi) $(if [ "$BUILD_CONFIG" == "gczeal" ]; then echo "--enable-gczeal"; fi)
script:
  - travis_wait 60 make V= -k $MAKE_ARGS || true
  - if [ "$BUILD_CONFIG" == "gczeal" ]; then export JS_GC_MAX_ZEAL=1; fi
  - ./deps/spidershim/scripts/run-tests.py
notifications:
  email: true
env:
  global:
    - LANG="en_US.UTF-8"
