language: cpp
sudo: false
#compiler:
  #- gcc
  #- clang
env:
  - BUILD_CONFIG=normal
  - BUILD_CONFIG=gczeal
dist: trusty
#os:
  #- linux
  #- osx
cache:
  - ccache
  - apt
addons:
  apt:
    packages:
      - autoconf2.13
      - yasm
      #- gcc-4.8
      #- g++-4.8
matrix:
  include:
    - os: linux
      compiler: clang

    - os: osx
      compiler: clang-3.8
      before_install:
        - brew update
        - brew tap homebrew/versions
        - travis_wait brew install llvm38 --with-asan
      install: export CC=clang-3.8 CXX=clang++-3.8
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install autoconf213 yasm; fi
before_script:
  - ./configure --debug --engine=spidermonkey --enable-asan $(if [ "$BUILD_CONFIG" == "gczeal" ]; then echo "--enable-gczeal"; fi)
script:
  - make V= -k || true
  - if [ "$BUILD_CONFIG" == "gczeal" ]; then export JS_GC_MAX_ZEAL=1; fi
  - ./deps/spidershim/scripts/run-tests.py
notifications:
  email: true
env:
  global:
    - LANG="en_US.UTF-8"
